{
 "title": "CRD Controller",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "project-controller-manager-metrics-service"
   },
   { "name": "name", "label": "name" }
  ]
 },
 "panels": [
  {
   "title": "Workqueue (controller-runtime default metrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Current WorkQueue Depth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_depth{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Seconds For Items Stay In Queue (before being requested) (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"$job.*\", name=~\"$name.*\"}[5m])) by (instance, name, le))",
     "legendFormat": "P50 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"$job.*\", name=~\"$name.*\"}[5m])) by (instance, name, le))",
     "legendFormat": "P90 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"$job.*\", name=~\"$name.*\"}[5m])) by (instance, name, le))",
     "legendFormat": "P99 {{name}} {{instance}} "
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"project-controller-manager-metrics-service\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Current Unfinished Seconds",
   "type": "gauge",
   "description": "How many seconds of work has done that is in progress and hasn't been observed by work_duration.\nLarge values indicate stuck threads.\nOne can deduce the number of stuck threads by observing the rate at which this increases.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(workqueue_unfinished_work_seconds{job=~\"$job.*\"}[5m])"
    }
   ]
  },
  {
   "title": "Seconds Processing Items From WorkQueue (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_work_duration_seconds_bucket{job=~\"$job.*\"}[5m])) by (instance, name, le))",
     "legendFormat": "P50 {{name}} {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_work_duration_seconds_bucket{job=~\"$job.*\"}[5m])) by (instance, name, le))",
     "legendFormat": "P90 {{name}} {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{job=~\"$job.*\"}[5m])) by (instance, name, le))",
     "legendFormat": "P99 {{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Work Queue Retries Rate",
   "type": "timeseries",
   "description": "Total number of retries handled by workqueue",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=\"project-controller-manager-metrics-service\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  { "title": "Reconciliation Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Number of currently used workers per controller",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{job=\"$job\"}",
     "legendFormat": "{{controller}} {{instance}}"
    }
   ]
  },
  {
   "title": "Reconciliation Duration Per Controller (P50, P90, P99)",
   "type": "timeseries",
   "description": "Cumulative counters for the observation buckets (Length of time per reconciliation per controller)",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\"}[5m])) by (instance, name, le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\"}[5m])) by (instance, name, le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\"}[5m])) by (instance, name, le))",
     "legendFormat": "P99"
    },
    { "expr": "workqueue", "legendFormat": "P99" }
   ]
  },
  {
   "title": "Reconciliation Error Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=\"$job\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resource Usage (relative k8s metrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Post Request Latency Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(rest_client_request_latency_seconds_bucket{job=\"project-controller-manager-metrics-service\", verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "P50 {{verb}} {{url}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rest_client_request_latency_seconds_bucket{job=\"project-controller-manager-metrics-service\", verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "P90 {{verb}} {{url}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=\"project-controller-manager-metrics-service\", verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "P99 {{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Controller CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"project-system\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"project-system\", resource=\"cpu\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"project-system\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Get Request Latency Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(rest_client_request_latency_seconds_bucket{job=\"project-controller-manager-metrics-service\", verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "P50 {{verb}} {{url}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rest_client_request_latency_seconds_bucket{job=\"project-controller-manager-metrics-service\", verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "P90 {{verb}} {{url}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=\"project-controller-manager-metrics-service\", verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "P99 {{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Controller Memory Usage(WSS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"project-system\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"project-system\", resource=\"memory\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"project-system\", resource=\"memory\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  }
 ]
}