apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"control-plane":"controller-manager"},"name":"project-controller-manager-metrics-monitor","namespace":"project-system"},"spec":{"endpoints":[{"bearerTokenFile":"/var/run/secrets/kubernetes.io/serviceaccount/token","path":"/metrics","port":"https","scheme":"https","tlsConfig":{"insecureSkipVerify":true}}],"selector":{"matchLabels":{"control-plane":"controller-manager"}}}}
  creationTimestamp: "2022-03-05T18:20:27Z"
  generation: 1
  labels:
    control-plane: controller-manager
  name: project-controller-manager-metrics-monitor
  namespace: monitoring
  resourceVersion: "58162"
  uid: b68136f6-70de-4aa4-8837-4d7251214dd8
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: controller-manager

